
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://strfwngnwunldkkcdpgx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InN0cmZ3bmdud3VubGRra2NkcGd4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM3MzQ4MDEsImV4cCI6MjA1OTMxMDgwMX0.vHK3cs5OTDU_equjIZfNfMhNfd9PYCDIFzpa9ebERQs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    persistSession: true,
    autoRefreshToken: true,
  }
});
